Update _index.md
docker/get-involved pull request #40
Opened 2021-08-12 08:39 UTC by 0904-mansi

in this commit, I have added Beginner-friendly issues and how to solve them.

2021-08-12 09:50 UTC, gauravgahlot requested changes
Welcome to the community @0904-mansi. :rocket: 

I have provided some feedback on the changes. Please feel free to put out any questions you may have. Thanks.

2021-08-12 09:50 UTC, gauravgahlot commented on content/en/docs/CommunityLeaders/EventHandbooks/Docker101/gettingstarted/_index.md
> +###  If You Are Facing This Error
```suggestion
## Troubleshooting
```

2021-08-12 09:50 UTC, gauravgahlot commented on content/en/docs/CommunityLeaders/EventHandbooks/Docker101/gettingstarted/_index.md
> +## Add "sudo" Before Run Any Docker Command
While both the solutions you have provided will work, but these are not recommended. You may want to check out this document on the Docker website: [https://docs.docker.com/engine/install/linux-postinstall/](https://docs.docker.com/engine/install/linux-postinstall/).

2021-08-13 01:12 UTC, ajeetraina commented
@0904-mansi Most of these tutorials are PWD based and we don't need sudo fo such environments.

2021-08-13 04:46 UTC, 0904-mansi commented
> @0904-mansi Most of these tutorials are PWD based and we don't need sudo fo such environments.

ok sir ☹

2021-09-02 07:10 UTC, closed without merging